namespace yurtprojesi
{
    partial class Form13
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form13));
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.tbGender = new Bunifu.Framework.UI.BunifuDropdown();
            this.tbDepartment = new Bunifu.Framework.UI.BunifuDropdown();
            this.tbAddress = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.btnEdit = new Bunifu.Framework.UI.BunifuFlatButton();
            this.tbPTel = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.tbPLastName = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.tbPFirstName = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.tbRoomNo = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.tbTelephone = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.tbEmail = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.tbLastName = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.tbFirstName = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.dgStudent = new System.Windows.Forms.DataGridView();
            this.tbSearch = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lblID = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.dgStudent)).BeginInit();
            this.SuspendLayout();
            // 
            // tbGender
            // 
            this.tbGender.BackColor = System.Drawing.Color.Transparent;
            this.tbGender.BorderRadius = 3;
            this.tbGender.DisabledColor = System.Drawing.Color.Gray;
            this.tbGender.ForeColor = System.Drawing.Color.White;
            this.tbGender.items = new string[] {
        "Gender...",
        "Male",
        "Famale"};
            this.tbGender.Location = new System.Drawing.Point(20, 288);
            this.tbGender.Name = "tbGender";
            this.tbGender.NomalColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(139)))), ((int)(((byte)(87)))));
            this.tbGender.onHoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(129)))), ((int)(((byte)(77)))));
            this.tbGender.selectedIndex = -1;
            this.tbGender.Size = new System.Drawing.Size(176, 39);
            this.tbGender.TabIndex = 110;
            // 
            // tbDepartment
            // 
            this.tbDepartment.BackColor = System.Drawing.Color.Transparent;
            this.tbDepartment.BorderRadius = 3;
            this.tbDepartment.DisabledColor = System.Drawing.Color.Gray;
            this.tbDepartment.ForeColor = System.Drawing.Color.White;
            this.tbDepartment.items = new string[] {
        "Select Department",
        "Computer Engineering",
        "Software Engineering",
        "Industry Engineering",
        "Electrical and Electronics Engineering",
        "Food Engineering",
        "Medicine",
        "Business"};
            this.tbDepartment.Location = new System.Drawing.Point(20, 328);
            this.tbDepartment.Name = "tbDepartment";
            this.tbDepartment.NomalColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(139)))), ((int)(((byte)(87)))));
            this.tbDepartment.onHoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(129)))), ((int)(((byte)(77)))));
            this.tbDepartment.selectedIndex = -1;
            this.tbDepartment.Size = new System.Drawing.Size(176, 39);
            this.tbDepartment.TabIndex = 109;
            // 
            // tbAddress
            // 
            this.tbAddress.AcceptsReturn = false;
            this.tbAddress.AcceptsTab = false;
            this.tbAddress.AnimationSpeed = 200;
            this.tbAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbAddress.BackColor = System.Drawing.Color.Transparent;
            this.tbAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbAddress.BackgroundImage")));
            this.tbAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.tbAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbAddress.BorderRadius = 1;
            this.tbAddress.BorderThickness = 1;
            this.tbAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.tbAddress.DefaultText = "";
            this.tbAddress.FillColor = System.Drawing.SystemColors.Control;
            this.tbAddress.HideSelection = true;
            this.tbAddress.IconLeft = null;
            this.tbAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.IconPadding = 10;
            this.tbAddress.IconRight = null;
            this.tbAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbAddress.Lines = new string[0];
            this.tbAddress.Location = new System.Drawing.Point(200, 249);
            this.tbAddress.Margin = new System.Windows.Forms.Padding(2);
            this.tbAddress.MaxLength = 32767;
            this.tbAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbAddress.Modified = false;
            this.tbAddress.Multiline = false;
            this.tbAddress.Name = "tbAddress";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbAddress.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.SystemColors.Control;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbAddress.OnIdleState = stateProperties4;
            this.tbAddress.PasswordChar = '\0';
            this.tbAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbAddress.PlaceholderText = "Address";
            this.tbAddress.ReadOnly = false;
            this.tbAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbAddress.SelectedText = "";
            this.tbAddress.SelectionLength = 0;
            this.tbAddress.SelectionStart = 0;
            this.tbAddress.ShortcutsEnabled = true;
            this.tbAddress.Size = new System.Drawing.Size(176, 157);
            this.tbAddress.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.tbAddress.TabIndex = 108;
            this.tbAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbAddress.TextMarginBottom = 0;
            this.tbAddress.TextMarginLeft = 5;
            this.tbAddress.TextMarginTop = 0;
            this.tbAddress.TextPlaceholder = "Address";
            this.tbAddress.UseSystemPasswordChar = false;
            this.tbAddress.WordWrap = true;
            // 
            // btnEdit
            // 
            this.btnEdit.Active = false;
            this.btnEdit.Activecolor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(139)))), ((int)(((byte)(87)))));
            this.btnEdit.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(139)))), ((int)(((byte)(87)))));
            this.btnEdit.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.btnEdit.BorderRadius = 0;
            this.btnEdit.ButtonText = "     Edit";
            this.btnEdit.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnEdit.DisabledColor = System.Drawing.Color.Gray;
            this.btnEdit.Iconcolor = System.Drawing.Color.Transparent;
            this.btnEdit.Iconimage = ((System.Drawing.Image)(resources.GetObject("btnEdit.Iconimage")));
            this.btnEdit.Iconimage_right = null;
            this.btnEdit.Iconimage_right_Selected = null;
            this.btnEdit.Iconimage_Selected = null;
            this.btnEdit.IconMarginLeft = 0;
            this.btnEdit.IconMarginRight = 0;
            this.btnEdit.IconRightVisible = true;
            this.btnEdit.IconRightZoom = 0D;
            this.btnEdit.IconVisible = true;
            this.btnEdit.IconZoom = 45D;
            this.btnEdit.IsTab = false;
            this.btnEdit.Location = new System.Drawing.Point(200, 430);
            this.btnEdit.Margin = new System.Windows.Forms.Padding(8, 7, 8, 7);
            this.btnEdit.Name = "btnEdit";
            this.btnEdit.Normalcolor = System.Drawing.Color.FromArgb(((int)(((byte)(46)))), ((int)(((byte)(139)))), ((int)(((byte)(87)))));
            this.btnEdit.OnHovercolor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(129)))), ((int)(((byte)(77)))));
            this.btnEdit.OnHoverTextColor = System.Drawing.Color.White;
            this.btnEdit.selected = false;
            this.btnEdit.Size = new System.Drawing.Size(176, 43);
            this.btnEdit.TabIndex = 106;
            this.btnEdit.Text = "     Edit";
            this.btnEdit.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEdit.Textcolor = System.Drawing.Color.White;
            this.btnEdit.TextFont = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEdit.Click += new System.EventHandler(this.btnEdit_Click);
            this.btnEdit.MouseClick += new System.Windows.Forms.MouseEventHandler(this.btnEdit_MouseClick);
            // 
            // tbPTel
            // 
            this.tbPTel.AcceptsReturn = false;
            this.tbPTel.AcceptsTab = false;
            this.tbPTel.AnimationSpeed = 200;
            this.tbPTel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbPTel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbPTel.BackColor = System.Drawing.Color.Transparent;
            this.tbPTel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbPTel.BackgroundImage")));
            this.tbPTel.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbPTel.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.tbPTel.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbPTel.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbPTel.BorderRadius = 1;
            this.tbPTel.BorderThickness = 1;
            this.tbPTel.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbPTel.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPTel.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.tbPTel.DefaultText = "";
            this.tbPTel.FillColor = System.Drawing.SystemColors.Control;
            this.tbPTel.HideSelection = true;
            this.tbPTel.IconLeft = null;
            this.tbPTel.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPTel.IconPadding = 10;
            this.tbPTel.IconRight = null;
            this.tbPTel.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPTel.Lines = new string[0];
            this.tbPTel.Location = new System.Drawing.Point(200, 210);
            this.tbPTel.Margin = new System.Windows.Forms.Padding(2);
            this.tbPTel.MaxLength = 32767;
            this.tbPTel.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbPTel.Modified = false;
            this.tbPTel.Multiline = false;
            this.tbPTel.Name = "tbPTel";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPTel.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPTel.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPTel.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.SystemColors.Control;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPTel.OnIdleState = stateProperties8;
            this.tbPTel.PasswordChar = '\0';
            this.tbPTel.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPTel.PlaceholderText = "Telephone";
            this.tbPTel.ReadOnly = false;
            this.tbPTel.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbPTel.SelectedText = "";
            this.tbPTel.SelectionLength = 0;
            this.tbPTel.SelectionStart = 0;
            this.tbPTel.ShortcutsEnabled = true;
            this.tbPTel.Size = new System.Drawing.Size(176, 38);
            this.tbPTel.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.tbPTel.TabIndex = 107;
            this.tbPTel.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbPTel.TextMarginBottom = 0;
            this.tbPTel.TextMarginLeft = 5;
            this.tbPTel.TextMarginTop = 0;
            this.tbPTel.TextPlaceholder = "Telephone";
            this.tbPTel.UseSystemPasswordChar = false;
            this.tbPTel.WordWrap = true;
            // 
            // tbPLastName
            // 
            this.tbPLastName.AcceptsReturn = false;
            this.tbPLastName.AcceptsTab = false;
            this.tbPLastName.AnimationSpeed = 200;
            this.tbPLastName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbPLastName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbPLastName.BackColor = System.Drawing.Color.Transparent;
            this.tbPLastName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbPLastName.BackgroundImage")));
            this.tbPLastName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbPLastName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.tbPLastName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbPLastName.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbPLastName.BorderRadius = 1;
            this.tbPLastName.BorderThickness = 1;
            this.tbPLastName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbPLastName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPLastName.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.tbPLastName.DefaultText = "";
            this.tbPLastName.FillColor = System.Drawing.SystemColors.Control;
            this.tbPLastName.HideSelection = true;
            this.tbPLastName.IconLeft = null;
            this.tbPLastName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPLastName.IconPadding = 10;
            this.tbPLastName.IconRight = null;
            this.tbPLastName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPLastName.Lines = new string[0];
            this.tbPLastName.Location = new System.Drawing.Point(200, 171);
            this.tbPLastName.Margin = new System.Windows.Forms.Padding(2);
            this.tbPLastName.MaxLength = 32767;
            this.tbPLastName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbPLastName.Modified = false;
            this.tbPLastName.Multiline = false;
            this.tbPLastName.Name = "tbPLastName";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPLastName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPLastName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPLastName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.SystemColors.Control;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPLastName.OnIdleState = stateProperties12;
            this.tbPLastName.PasswordChar = '\0';
            this.tbPLastName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPLastName.PlaceholderText = "Last Name";
            this.tbPLastName.ReadOnly = false;
            this.tbPLastName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbPLastName.SelectedText = "";
            this.tbPLastName.SelectionLength = 0;
            this.tbPLastName.SelectionStart = 0;
            this.tbPLastName.ShortcutsEnabled = true;
            this.tbPLastName.Size = new System.Drawing.Size(176, 38);
            this.tbPLastName.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.tbPLastName.TabIndex = 105;
            this.tbPLastName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbPLastName.TextMarginBottom = 0;
            this.tbPLastName.TextMarginLeft = 5;
            this.tbPLastName.TextMarginTop = 0;
            this.tbPLastName.TextPlaceholder = "Last Name";
            this.tbPLastName.UseSystemPasswordChar = false;
            this.tbPLastName.WordWrap = true;
            // 
            // tbPFirstName
            // 
            this.tbPFirstName.AcceptsReturn = false;
            this.tbPFirstName.AcceptsTab = false;
            this.tbPFirstName.AnimationSpeed = 200;
            this.tbPFirstName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbPFirstName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbPFirstName.BackColor = System.Drawing.Color.Transparent;
            this.tbPFirstName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbPFirstName.BackgroundImage")));
            this.tbPFirstName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbPFirstName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.tbPFirstName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbPFirstName.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbPFirstName.BorderRadius = 1;
            this.tbPFirstName.BorderThickness = 1;
            this.tbPFirstName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbPFirstName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPFirstName.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.tbPFirstName.DefaultText = "";
            this.tbPFirstName.FillColor = System.Drawing.SystemColors.Control;
            this.tbPFirstName.HideSelection = true;
            this.tbPFirstName.IconLeft = null;
            this.tbPFirstName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPFirstName.IconPadding = 10;
            this.tbPFirstName.IconRight = null;
            this.tbPFirstName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbPFirstName.Lines = new string[0];
            this.tbPFirstName.Location = new System.Drawing.Point(200, 132);
            this.tbPFirstName.Margin = new System.Windows.Forms.Padding(2);
            this.tbPFirstName.MaxLength = 32767;
            this.tbPFirstName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbPFirstName.Modified = false;
            this.tbPFirstName.Multiline = false;
            this.tbPFirstName.Name = "tbPFirstName";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPFirstName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPFirstName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPFirstName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.SystemColors.Control;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbPFirstName.OnIdleState = stateProperties16;
            this.tbPFirstName.PasswordChar = '\0';
            this.tbPFirstName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbPFirstName.PlaceholderText = "First Name";
            this.tbPFirstName.ReadOnly = false;
            this.tbPFirstName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbPFirstName.SelectedText = "";
            this.tbPFirstName.SelectionLength = 0;
            this.tbPFirstName.SelectionStart = 0;
            this.tbPFirstName.ShortcutsEnabled = true;
            this.tbPFirstName.Size = new System.Drawing.Size(176, 38);
            this.tbPFirstName.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.tbPFirstName.TabIndex = 104;
            this.tbPFirstName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbPFirstName.TextMarginBottom = 0;
            this.tbPFirstName.TextMarginLeft = 5;
            this.tbPFirstName.TextMarginTop = 0;
            this.tbPFirstName.TextPlaceholder = "First Name";
            this.tbPFirstName.UseSystemPasswordChar = false;
            this.tbPFirstName.WordWrap = true;
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Segoe UI Semibold", 10.8F);
            this.label12.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.label12.Location = new System.Drawing.Point(197, 100);
            this.label12.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(89, 20);
            this.label12.TabIndex = 103;
            this.label12.Text = "Parent Info:";
            // 
            // tbRoomNo
            // 
            this.tbRoomNo.AcceptsReturn = false;
            this.tbRoomNo.AcceptsTab = false;
            this.tbRoomNo.AnimationSpeed = 200;
            this.tbRoomNo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbRoomNo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbRoomNo.BackColor = System.Drawing.Color.Transparent;
            this.tbRoomNo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbRoomNo.BackgroundImage")));
            this.tbRoomNo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbRoomNo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.tbRoomNo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbRoomNo.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbRoomNo.BorderRadius = 1;
            this.tbRoomNo.BorderThickness = 1;
            this.tbRoomNo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbRoomNo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbRoomNo.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.tbRoomNo.DefaultText = "";
            this.tbRoomNo.FillColor = System.Drawing.SystemColors.Control;
            this.tbRoomNo.HideSelection = true;
            this.tbRoomNo.IconLeft = null;
            this.tbRoomNo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbRoomNo.IconPadding = 10;
            this.tbRoomNo.IconRight = null;
            this.tbRoomNo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbRoomNo.Lines = new string[0];
            this.tbRoomNo.Location = new System.Drawing.Point(20, 368);
            this.tbRoomNo.Margin = new System.Windows.Forms.Padding(2);
            this.tbRoomNo.MaxLength = 32767;
            this.tbRoomNo.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbRoomNo.Modified = false;
            this.tbRoomNo.Multiline = false;
            this.tbRoomNo.Name = "tbRoomNo";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbRoomNo.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbRoomNo.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbRoomNo.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.SystemColors.Control;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbRoomNo.OnIdleState = stateProperties20;
            this.tbRoomNo.PasswordChar = '\0';
            this.tbRoomNo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbRoomNo.PlaceholderText = "Room No";
            this.tbRoomNo.ReadOnly = false;
            this.tbRoomNo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbRoomNo.SelectedText = "";
            this.tbRoomNo.SelectionLength = 0;
            this.tbRoomNo.SelectionStart = 0;
            this.tbRoomNo.ShortcutsEnabled = true;
            this.tbRoomNo.Size = new System.Drawing.Size(176, 38);
            this.tbRoomNo.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.tbRoomNo.TabIndex = 102;
            this.tbRoomNo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbRoomNo.TextMarginBottom = 0;
            this.tbRoomNo.TextMarginLeft = 5;
            this.tbRoomNo.TextMarginTop = 0;
            this.tbRoomNo.TextPlaceholder = "Room No";
            this.tbRoomNo.UseSystemPasswordChar = false;
            this.tbRoomNo.WordWrap = true;
            // 
            // tbTelephone
            // 
            this.tbTelephone.AcceptsReturn = false;
            this.tbTelephone.AcceptsTab = false;
            this.tbTelephone.AnimationSpeed = 200;
            this.tbTelephone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbTelephone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbTelephone.BackColor = System.Drawing.Color.Transparent;
            this.tbTelephone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbTelephone.BackgroundImage")));
            this.tbTelephone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbTelephone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.tbTelephone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbTelephone.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbTelephone.BorderRadius = 1;
            this.tbTelephone.BorderThickness = 1;
            this.tbTelephone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbTelephone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbTelephone.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.tbTelephone.DefaultText = "";
            this.tbTelephone.FillColor = System.Drawing.SystemColors.Control;
            this.tbTelephone.HideSelection = true;
            this.tbTelephone.IconLeft = null;
            this.tbTelephone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbTelephone.IconPadding = 10;
            this.tbTelephone.IconRight = null;
            this.tbTelephone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbTelephone.Lines = new string[0];
            this.tbTelephone.Location = new System.Drawing.Point(20, 249);
            this.tbTelephone.Margin = new System.Windows.Forms.Padding(2);
            this.tbTelephone.MaxLength = 32767;
            this.tbTelephone.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbTelephone.Modified = false;
            this.tbTelephone.Multiline = false;
            this.tbTelephone.Name = "tbTelephone";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbTelephone.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Empty;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbTelephone.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbTelephone.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.SystemColors.Control;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbTelephone.OnIdleState = stateProperties24;
            this.tbTelephone.PasswordChar = '\0';
            this.tbTelephone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbTelephone.PlaceholderText = "Telephone";
            this.tbTelephone.ReadOnly = false;
            this.tbTelephone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbTelephone.SelectedText = "";
            this.tbTelephone.SelectionLength = 0;
            this.tbTelephone.SelectionStart = 0;
            this.tbTelephone.ShortcutsEnabled = true;
            this.tbTelephone.Size = new System.Drawing.Size(176, 38);
            this.tbTelephone.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.tbTelephone.TabIndex = 101;
            this.tbTelephone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbTelephone.TextMarginBottom = 0;
            this.tbTelephone.TextMarginLeft = 5;
            this.tbTelephone.TextMarginTop = 0;
            this.tbTelephone.TextPlaceholder = "Telephone";
            this.tbTelephone.UseSystemPasswordChar = false;
            this.tbTelephone.WordWrap = true;
            // 
            // tbEmail
            // 
            this.tbEmail.AcceptsReturn = false;
            this.tbEmail.AcceptsTab = false;
            this.tbEmail.AnimationSpeed = 200;
            this.tbEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbEmail.BackColor = System.Drawing.Color.Transparent;
            this.tbEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbEmail.BackgroundImage")));
            this.tbEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.tbEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbEmail.BorderRadius = 1;
            this.tbEmail.BorderThickness = 1;
            this.tbEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.tbEmail.DefaultText = "";
            this.tbEmail.FillColor = System.Drawing.SystemColors.Control;
            this.tbEmail.HideSelection = true;
            this.tbEmail.IconLeft = null;
            this.tbEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.IconPadding = 10;
            this.tbEmail.IconRight = null;
            this.tbEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbEmail.Lines = new string[0];
            this.tbEmail.Location = new System.Drawing.Point(20, 210);
            this.tbEmail.Margin = new System.Windows.Forms.Padding(2);
            this.tbEmail.MaxLength = 32767;
            this.tbEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbEmail.Modified = false;
            this.tbEmail.Multiline = false;
            this.tbEmail.Name = "tbEmail";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Empty;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbEmail.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.SystemColors.Control;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbEmail.OnIdleState = stateProperties28;
            this.tbEmail.PasswordChar = '\0';
            this.tbEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbEmail.PlaceholderText = "Email";
            this.tbEmail.ReadOnly = false;
            this.tbEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbEmail.SelectedText = "";
            this.tbEmail.SelectionLength = 0;
            this.tbEmail.SelectionStart = 0;
            this.tbEmail.ShortcutsEnabled = true;
            this.tbEmail.Size = new System.Drawing.Size(176, 38);
            this.tbEmail.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.tbEmail.TabIndex = 100;
            this.tbEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbEmail.TextMarginBottom = 0;
            this.tbEmail.TextMarginLeft = 5;
            this.tbEmail.TextMarginTop = 0;
            this.tbEmail.TextPlaceholder = "Email";
            this.tbEmail.UseSystemPasswordChar = false;
            this.tbEmail.WordWrap = true;
            // 
            // tbLastName
            // 
            this.tbLastName.AcceptsReturn = false;
            this.tbLastName.AcceptsTab = false;
            this.tbLastName.AnimationSpeed = 200;
            this.tbLastName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbLastName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbLastName.BackColor = System.Drawing.Color.Transparent;
            this.tbLastName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbLastName.BackgroundImage")));
            this.tbLastName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbLastName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.tbLastName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbLastName.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbLastName.BorderRadius = 1;
            this.tbLastName.BorderThickness = 1;
            this.tbLastName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbLastName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastName.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.tbLastName.DefaultText = "";
            this.tbLastName.FillColor = System.Drawing.SystemColors.Control;
            this.tbLastName.HideSelection = true;
            this.tbLastName.IconLeft = null;
            this.tbLastName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastName.IconPadding = 10;
            this.tbLastName.IconRight = null;
            this.tbLastName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbLastName.Lines = new string[0];
            this.tbLastName.Location = new System.Drawing.Point(20, 171);
            this.tbLastName.Margin = new System.Windows.Forms.Padding(2);
            this.tbLastName.MaxLength = 32767;
            this.tbLastName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbLastName.Modified = false;
            this.tbLastName.Multiline = false;
            this.tbLastName.Name = "tbLastName";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastName.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Empty;
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.Empty;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbLastName.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastName.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.SystemColors.Control;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbLastName.OnIdleState = stateProperties32;
            this.tbLastName.PasswordChar = '\0';
            this.tbLastName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbLastName.PlaceholderText = "Last Name";
            this.tbLastName.ReadOnly = false;
            this.tbLastName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbLastName.SelectedText = "";
            this.tbLastName.SelectionLength = 0;
            this.tbLastName.SelectionStart = 0;
            this.tbLastName.ShortcutsEnabled = true;
            this.tbLastName.Size = new System.Drawing.Size(176, 38);
            this.tbLastName.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.tbLastName.TabIndex = 99;
            this.tbLastName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbLastName.TextMarginBottom = 0;
            this.tbLastName.TextMarginLeft = 5;
            this.tbLastName.TextMarginTop = 0;
            this.tbLastName.TextPlaceholder = "Last Name";
            this.tbLastName.UseSystemPasswordChar = false;
            this.tbLastName.WordWrap = true;
            // 
            // tbFirstName
            // 
            this.tbFirstName.AcceptsReturn = false;
            this.tbFirstName.AcceptsTab = false;
            this.tbFirstName.AnimationSpeed = 200;
            this.tbFirstName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbFirstName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbFirstName.BackColor = System.Drawing.Color.Transparent;
            this.tbFirstName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbFirstName.BackgroundImage")));
            this.tbFirstName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbFirstName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.tbFirstName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbFirstName.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbFirstName.BorderRadius = 1;
            this.tbFirstName.BorderThickness = 1;
            this.tbFirstName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbFirstName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstName.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.tbFirstName.DefaultText = "";
            this.tbFirstName.FillColor = System.Drawing.SystemColors.Control;
            this.tbFirstName.HideSelection = true;
            this.tbFirstName.IconLeft = null;
            this.tbFirstName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstName.IconPadding = 10;
            this.tbFirstName.IconRight = null;
            this.tbFirstName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbFirstName.Lines = new string[0];
            this.tbFirstName.Location = new System.Drawing.Point(20, 132);
            this.tbFirstName.Margin = new System.Windows.Forms.Padding(2);
            this.tbFirstName.MaxLength = 32767;
            this.tbFirstName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbFirstName.Modified = false;
            this.tbFirstName.Multiline = false;
            this.tbFirstName.Name = "tbFirstName";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstName.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Empty;
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.Empty;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbFirstName.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstName.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.SystemColors.Control;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbFirstName.OnIdleState = stateProperties36;
            this.tbFirstName.PasswordChar = '\0';
            this.tbFirstName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbFirstName.PlaceholderText = "First Name";
            this.tbFirstName.ReadOnly = false;
            this.tbFirstName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbFirstName.SelectedText = "";
            this.tbFirstName.SelectionLength = 0;
            this.tbFirstName.SelectionStart = 0;
            this.tbFirstName.ShortcutsEnabled = true;
            this.tbFirstName.Size = new System.Drawing.Size(176, 38);
            this.tbFirstName.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.tbFirstName.TabIndex = 98;
            this.tbFirstName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbFirstName.TextMarginBottom = 0;
            this.tbFirstName.TextMarginLeft = 5;
            this.tbFirstName.TextMarginTop = 0;
            this.tbFirstName.TextPlaceholder = "First Name";
            this.tbFirstName.UseSystemPasswordChar = false;
            this.tbFirstName.WordWrap = true;
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Segoe UI Semibold", 10.8F);
            this.label11.ForeColor = System.Drawing.SystemColors.MenuHighlight;
            this.label11.Location = new System.Drawing.Point(16, 100);
            this.label11.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(97, 20);
            this.label11.TabIndex = 97;
            this.label11.Text = "Student Info:";
            // 
            // dgStudent
            // 
            this.dgStudent.BackgroundColor = System.Drawing.SystemColors.Control;
            this.dgStudent.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgStudent.Location = new System.Drawing.Point(381, 30);
            this.dgStudent.Name = "dgStudent";
            this.dgStudent.Size = new System.Drawing.Size(351, 443);
            this.dgStudent.TabIndex = 111;
            this.dgStudent.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgStudent_CellClick);
            // 
            // tbSearch
            // 
            this.tbSearch.AcceptsReturn = false;
            this.tbSearch.AcceptsTab = false;
            this.tbSearch.AnimationSpeed = 200;
            this.tbSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSearch.BackColor = System.Drawing.Color.Transparent;
            this.tbSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSearch.BackgroundImage")));
            this.tbSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.tbSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbSearch.BorderRadius = 1;
            this.tbSearch.BorderThickness = 1;
            this.tbSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.tbSearch.DefaultText = "";
            this.tbSearch.FillColor = System.Drawing.SystemColors.Control;
            this.tbSearch.HideSelection = true;
            this.tbSearch.IconLeft = null;
            this.tbSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.IconPadding = 12;
            this.tbSearch.IconRight = ((System.Drawing.Image)(resources.GetObject("tbSearch.IconRight")));
            this.tbSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.Lines = new string[0];
            this.tbSearch.Location = new System.Drawing.Point(20, 30);
            this.tbSearch.Margin = new System.Windows.Forms.Padding(2);
            this.tbSearch.MaxLength = 32767;
            this.tbSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSearch.Modified = false;
            this.tbSearch.Multiline = false;
            this.tbSearch.Name = "tbSearch";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.Empty;
            stateProperties38.FillColor = System.Drawing.Color.White;
            stateProperties38.ForeColor = System.Drawing.Color.Empty;
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSearch.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.SystemColors.Control;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnIdleState = stateProperties40;
            this.tbSearch.PasswordChar = '\0';
            this.tbSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSearch.PlaceholderText = "Search by Name...";
            this.tbSearch.ReadOnly = false;
            this.tbSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSearch.SelectedText = "";
            this.tbSearch.SelectionLength = 0;
            this.tbSearch.SelectionStart = 0;
            this.tbSearch.ShortcutsEnabled = true;
            this.tbSearch.Size = new System.Drawing.Size(356, 46);
            this.tbSearch.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.tbSearch.TabIndex = 112;
            this.tbSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSearch.TextMarginBottom = 0;
            this.tbSearch.TextMarginLeft = 5;
            this.tbSearch.TextMarginTop = 0;
            this.tbSearch.TextPlaceholder = "Search by Name...";
            this.tbSearch.UseSystemPasswordChar = false;
            this.tbSearch.WordWrap = true;
            this.tbSearch.TextChange += new System.EventHandler(this.tbSearch_TextChange);
            // 
            // lblID
            // 
            this.lblID.AutoSize = true;
            this.lblID.Location = new System.Drawing.Point(12, 482);
            this.lblID.Name = "lblID";
            this.lblID.Size = new System.Drawing.Size(35, 13);
            this.lblID.TabIndex = 113;
            this.lblID.Text = "label1";
            this.lblID.Visible = false;
            // 
            // Form13
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(750, 504);
            this.Controls.Add(this.lblID);
            this.Controls.Add(this.tbSearch);
            this.Controls.Add(this.dgStudent);
            this.Controls.Add(this.tbGender);
            this.Controls.Add(this.tbDepartment);
            this.Controls.Add(this.tbAddress);
            this.Controls.Add(this.btnEdit);
            this.Controls.Add(this.tbPTel);
            this.Controls.Add(this.tbPLastName);
            this.Controls.Add(this.tbPFirstName);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.tbRoomNo);
            this.Controls.Add(this.tbTelephone);
            this.Controls.Add(this.tbEmail);
            this.Controls.Add(this.tbLastName);
            this.Controls.Add(this.tbFirstName);
            this.Controls.Add(this.label11);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form13";
            this.Text = "Form13";
            this.Load += new System.EventHandler(this.Form13_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgStudent)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        public Bunifu.Framework.UI.BunifuDropdown tbGender;
        public Bunifu.Framework.UI.BunifuDropdown tbDepartment;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox tbAddress;
        public Bunifu.Framework.UI.BunifuFlatButton btnEdit;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox tbPTel;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox tbPLastName;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox tbPFirstName;
        public System.Windows.Forms.Label label12;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox tbRoomNo;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox tbTelephone;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox tbEmail;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox tbLastName;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox tbFirstName;
        public System.Windows.Forms.Label label11;
        public System.Windows.Forms.DataGridView dgStudent;
        public Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox tbSearch;
        private System.Windows.Forms.Label lblID;
    }
}